---

apiVersion: v1
kind: Namespace
metadata:
  name: argo-notif

---

apiVersion: batch/v1
kind: Job
metadata:
  name: sock-notif-syncing
  namespace: argo-notif
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: slack-notif
        image: technosophos/slack-notify
        env:
        - name: SLACK_MESSAGE
          value: "Syncing `sock-shop` app."
        envFrom:
        - secretRef:
            name: slack-webhook
---

apiVersion: batch/v1
kind: Job
metadata:
  name: sock-notif-succeed
  namespace: argo-notif
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: slack-notif
        image: technosophos/slack-notify
        env:
        - name: SLACK_MESSAGE
          value: "`sock-shop` app is synced successfully."
        envFrom:
        - secretRef:
            name: slack-webhook
---

apiVersion: batch/v1
kind: Job
metadata:
  name: sock-notif-failed
  namespace: argo-notif
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: slack-notif
        image: technosophos/slack-notify
        env:
        - name: SLACK_MESSAGE
          value: "A problem has occurred during sync of `sock-shop` app."
        envFrom:
        - secretRef:
            name: slack-webhook
